### ISSUE TITLE
GH action fails with "Unsupported sceptre version"

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/github-ci-action#5]
We have the following GH workflow:

```
name: "deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  sceptre-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::XXXXXXXX:role/sagebase-github-oidc-sage-ProviderRolescicompprovi-BWN39S0CL6IZ
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1800
      - name: 'Sceptre Launch prod'
        uses: Sceptre/github-ci-action@v2.2.0
        with:
          sceptre_version: 4.0.2
          sceptre_plugins: >-
            sceptre-ssm-resolver==1.2.2
          sceptre_subcommand: launch --prune --yes prod
```

The 'Sceptre Launch prod' step fails with the following message..
```
Run Sceptre/github-ci-action@v2.2.0
  with:
    sceptre_version: 4.0.[2](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:2)
    sceptre_plugins: sceptre-ssm-resolver==1.2.2
    sceptre_subcommand: launch --prune --yes prod
    sceptre_troposphere: false
    sceptre_troposphere_version: 2.7.1
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***

/usr/bin/docker run --name c04421e11[3](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:3)8397632[4](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:4)8ba849ccb[5](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:5)d[6](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:6)ec93ec5_db208a
--label 6c0442 
--workdir /github/workspace 
--rm
-e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "INPUT_SCEPTRE_VERSION" -e "INPUT_SCEPTRE_PLUGINS" -e "INPUT_SCEPTRE_SUBCOMMAND" -e "INPUT_SCEPTRE_DIRECTORY" -e "INPUT_SCEPTRE_TROPOSPHERE" -e "INPUT_SCEPTRE_TROPOSPHERE_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true 
-v "/var/run/docker.sock":"/var/run/docker.sock" 
-v "/home/runner/work/_temp/_github_home":"/github/home" 
-v "/home/runner/work/_temp/_github_workflow":"/github/workflow" 
-v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" 
-v "/home/runner/work/scicomp-provisioner/scicomp-provisioner":"/github/workspace" 6c0442:1e113839[7](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:7)6324[8](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:8)ba84[9](https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/4702060854/jobs/8338875045#step:5:9)ccb5d6ec93ec5

Unsupported sceptre version
```
